#!/usr/bin/env bash
#comment
while IFS=':' read -r username password uid gid info home shell; do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
    echo "-----------------------------------"
done < /etc/passwd
