#!/usr/bin/env bash
#comment
# Set IFS (Internal Field Separator) to colon for parsing /etc/passwd entries
IFS=":"

# Read /etc/passwd file line by line
while read -r username password userid groupid userdesc homedir shell; do
    echo "The user $username is part of the $groupid gang, lives in $homedir, and rides $shell.$userid's place is protected by the passcode $password, more info about the user here: $userdesc"
done < /etc/passwd

