#!/usr/bin/env bash
#um

hour=1

while [ $hour -le 12 ]; do
	minute=1
	while [ $minute -le 59 ]; do
		printf "%02d\n" $minute
		((minute++))
	done
	echo "hour=$hour"
	((hour++))
done
minute=1
while [ $minute -le 59 ]; do
    printf "%02d\n" $minute
    ((minute++))
done
