#!/usr/bin/env bash
#um
hour=0
while [ $hour -le 12 ]; do
	echo "Hour: $hour"
	minute=1
	while [ $minute -le 59 ]; do
		echo "$minute"
		((minute++))
	done
	((hour++))
done
minute=1
while [ $minute -le 59 ]; do
    printf "%02d\n" $minute
    ((minute++))
done
